// GENERATED by zebkit. Do not edit.
// Regenerate with `zebkit build` after changing zebkit.config.json or variant JSON.
import { ZebkitElement } from 'zebkit/components';

export const zebkitConfig = {
  "zebkitVersion": "0.16.1",
  "themeName": "dynamowaves",
  "accessibility": {
    "delivery": "auto"
  },
  "components": {
    "accordion": false,
    "badge": false,
    "breadcrumb": false,
    "button": {
      "variants": [
        "ghost",
        "lg",
        "sm"
      ],
      "options": {
        "discoverToggledElementTimeout": 2000
      }
    },
    "card": false,
    "checkbox": false,
    "code-block": {
      "options": {
        "buttonVariant": "code-block-copy code-block-copy-size code-block-copy-motion",
        "checkboxVariant": false,
        "codeWrap": true,
        "copiedIcon": {
          "html": "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m5 12 4 4L19 6\"></path></svg>"
        },
        "copy": true,
        "copyIcon": {
          "html": "<svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"9\" y=\"9\" width=\"13\" height=\"13\" rx=\"2\"></rect><path d=\"M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1\"></path></svg>"
        },
        "label": "Code",
        "normalizeCode": true,
        "previewWrap": true,
        "showPreview": false,
        "split": false,
        "splitControl": "toggle",
        "splitPosition": 50,
        "tabsVariant": "code-block",
        "toggleVariant": false,
        "view": "code"
      }
    },
    "dialog": false,
    "disclosure": false,
    "input": false,
    "link": {
      "variants": [
        "subtle"
      ],
      "options": {
        "addRelNoopener": true,
        "internalHosts": [],
        "newTabHint": "(opens in a new tab)",
        "newTabIcon": {
          "text": "↗"
        },
        "openExternalInNewTab": false
      }
    },
    "menu": false,
    "menu-item": false,
    "pagination": false,
    "panel": false,
    "popover": false,
    "radio": false,
    "select": false,
    "tabs": {
      "variants": []
    },
    "tag": false,
    "textarea": false,
    "toast": false,
    "toast-region": false,
    "toggle": {
      "variants": []
    },
    "tooltip": false
  },
  "variants": [
    {
      "component": "button",
      "name": "code-block-copy",
      "axis": "style",
      "description": "Copy action colors and shape owned by Code Block.",
      "overrides": {
        "border-color": "{app.border-muted}",
        "border-color-active": "{app.border-emphasis}",
        "border-color-focus": "{app.border-emphasis}",
        "border-color-hover": "{app.border}",
        "border-radius": "{border.radius-sm}",
        "border-style": "{border.style}",
        "border-width": "0px",
        "canvas": "{code-block.bar-canvas}",
        "canvas-active": "{brand.200}",
        "canvas-focus": "{brand.100}",
        "canvas-hover": "{brand.100}",
        "cursor": "pointer",
        "ink": "{app.ink}",
        "ink-active": "{app.ink-emphasis}",
        "ink-focus": "{app.ink-emphasis}",
        "ink-hover": "{app.ink-emphasis}",
        "text-align": "center",
        "text-box-edge": "auto",
        "text-box-trim": "none",
        "text-decoration": "none"
      }
    },
    {
      "component": "button",
      "name": "code-block-copy-motion",
      "axis": "effect",
      "description": "Flat, restrained interaction motion for the Code Block Copy action.",
      "overrides": {
        "box-shadow": "{elevation.none}",
        "box-shadow-active": "{elevation.none}",
        "box-shadow-focus": "{elevation.none}",
        "box-shadow-hover": "{elevation.none}",
        "transform": "none",
        "transform-active": "none",
        "transform-focus": "none",
        "transform-hover": "none",
        "transition-delay": "0ms",
        "transition-duration": "150ms",
        "transition-property": "background-color, color, border-color, box-shadow, transform, outline",
        "transition-timing-function": "ease-out"
      }
    },
    {
      "component": "button",
      "name": "code-block-copy-size",
      "axis": "size",
      "description": "Compact target and typography for the Code Block Copy action.",
      "overrides": {
        "font-family": "{font-family.interface}",
        "font-size": "{font-size.xs}",
        "font-weight": "{font-weight.medium}",
        "gap": "{spacing.xs}",
        "icon-end-size": "{font-size.xs}",
        "icon-size": "{font-size.xs}",
        "icon-start-size": "{font-size.xs}",
        "letter-spacing": "{letter-spacing.normal}",
        "line-height": "{line-height.2}",
        "min-height": "{a11y.min-interaction-size}",
        "min-width": "{a11y.min-interaction-size}",
        "padding-block": "{spacing.xs}",
        "padding-block-end": "{spacing.xs}",
        "padding-block-start": "{spacing.xs}",
        "padding-inline": "{spacing.sm}",
        "padding-inline-end": "{spacing.sm}",
        "padding-inline-start": "{spacing.sm}",
        "text-transform": "none"
      }
    },
    {
      "component": "button",
      "name": "ghost",
      "axis": "style",
      "overrides": {
        "border-color": "transparent",
        "border-color-active": "transparent",
        "border-color-focus": "transparent",
        "border-color-hover": "transparent",
        "border-radius": "{border.radius-md}",
        "border-width": "0",
        "canvas": "transparent",
        "canvas-active": "{brand.ink-muted}",
        "canvas-disabled": "{disabled.canvas}",
        "canvas-focus": "{brand.ink-muted}",
        "canvas-hover": "{brand.ink-muted}",
        "ink": "{brand.ink}",
        "ink-active": "{brand.ink-emphasis}",
        "ink-disabled": "{disabled.ink}",
        "ink-focus": "{brand.ink-emphasis}",
        "ink-hover": "{brand.ink-emphasis}"
      }
    },
    {
      "component": "button",
      "name": "lg",
      "axis": "size",
      "description": "Larger type and padding.",
      "overrides": {
        "font-size": "{font-size.md}",
        "icon-size": "{spacing.105}",
        "padding-block": "{spacing.sm}",
        "padding-inline": "{spacing.md}"
      }
    },
    {
      "component": "button",
      "name": "sm",
      "axis": "size",
      "description": "Compact type, padding, and icon sizing.",
      "overrides": {
        "font-size": "{font-size.sm}",
        "icon-size": "{spacing.105}",
        "padding-block": "{spacing.xs}",
        "padding-inline": "{spacing.xs}"
      }
    },
    {
      "component": "button",
      "name": "wave-action",
      "axis": "style",
      "description": "Outlined, elevated action treatment matching the Dynamowaves demo controls.",
      "overrides": {
        "border-color": "{brand.canvas}",
        "border-color-active": "{brand.canvas}",
        "border-color-hover": "{brand.canvas}",
        "border-radius": "{border.radius-md}",
        "border-width": "{border.width-sm}",
        "canvas": "transparent",
        "canvas-active": "color-mix(in srgb, var(--zbk-brand-canvas-muted) 70%, transparent)",
        "canvas-hover": "color-mix(in srgb, var(--zbk-brand-canvas-muted) 32.5%, transparent)",
        "ink": "{brand.ink-emphasis}",
        "ink-active": "{brand.ink-emphasis}",
        "ink-hover": "{brand.ink-emphasis}"
      }
    },
    {
      "component": "button",
      "name": "wave-action-strong",
      "axis": "style",
      "description": "Filled action treatment for controls placed on branded demo surfaces.",
      "overrides": {
        "border-color": "{brand.canvas-subtle}",
        "border-color-active": "{brand.canvas-subtle}",
        "border-color-hover": "{brand.canvas-subtle}",
        "border-radius": "{border.radius-md}",
        "border-width": "0px",
        "canvas": "{brand.canvas-subtle}",
        "canvas-active": "{brand.canvas-subtle}",
        "canvas-hover": "{brand.canvas-subtle}",
        "ink": "{brand.ink-emphasis}",
        "ink-active": "{brand.ink-emphasis}",
        "ink-hover": "{brand.ink-emphasis}"
      }
    },
    {
      "component": "button",
      "name": "wave-pop",
      "axis": "effect",
      "description": "Offset blended surface that settles on hover and press for Dynamowaves actions.",
      "overrides": {
        "box-shadow": "var(--zbk-spacing-05) var(--zbk-spacing-05) 0 var(--zbk-spacing-2px) color-mix(in srgb, var(--zbk-brand-canvas-muted) 50%, transparent)",
        "box-shadow-active": "0 0 0 0 color-mix(in srgb, var(--zbk-brand-canvas-muted) 50%, transparent)",
        "box-shadow-disabled": "none",
        "box-shadow-focus": "0 0 0 0 color-mix(in srgb, var(--zbk-brand-canvas-muted) 50%, transparent)",
        "box-shadow-hover": "0 0 0 0 color-mix(in srgb, var(--zbk-brand-canvas-muted) 50%, transparent)",
        "transform": "none",
        "transform-active": "scale(.985)",
        "transform-disabled": "none",
        "transform-focus": "none",
        "transform-hover": "none",
        "transition-delay": "0ms",
        "transition-duration": "{transition.duration-default}",
        "transition-timing-function": "{transition.playful-fx-function-default}"
      }
    },
    {
      "component": "code-block",
      "name": "aaa",
      "axis": "accessibility",
      "description": "AAA code and chrome contrast, larger reading type, and full-size action targets.",
      "overrides": {
        "actions-gap": "{spacing.sm}",
        "bar-border-color": "{app.ink-emphasis}",
        "bar-font-size": "{font-size.sm}",
        "bar-gap": "{spacing.md}",
        "bar-ink": "{app.ink-emphasis}",
        "bar-padding-block": "{spacing.sm}",
        "bar-padding-inline": "{spacing.md}",
        "border-color": "{app.ink-emphasis}",
        "code-font-size": "{font-size.md}",
        "code-ink": "{app.ink-emphasis}",
        "code-padding-block": "{spacing.lg}",
        "code-padding-inline": "{spacing.lg}",
        "focus-color": "{info.ink}",
        "ink": "{app.ink-emphasis}",
        "preview-ink": "{app.ink-emphasis}",
        "preview-padding-block": "{spacing.lg}",
        "preview-padding-inline": "{spacing.lg}",
        "split-divider-ink": "{app.ink-emphasis}",
        "split-divider-ink-active": "{info.ink}",
        "split-divider-ink-hover": "{app.ink-emphasis}",
        "split-divider-target-size": "{spacing.xl}",
        "split-grip-border-color": "{app.ink-emphasis}",
        "split-grip-canvas": "{app.canvas}",
        "split-grip-ink": "{app.ink-emphasis}",
        "view-gap": "{spacing.sm}"
      }
    },
    {
      "component": "link",
      "name": "sm",
      "axis": "size",
      "description": "Compact type, padding, and icon sizing.",
      "overrides": {
        "font-size": "{font-size.sm}"
      }
    },
    {
      "component": "link",
      "name": "subtle",
      "axis": "style",
      "description": "No underline at rest; underline returns on hover so the affordance is never lost for keyboard and low-vision users.",
      "overrides": {
        "decoration-color-hover": "{action.ink}",
        "decoration-line": "none",
        "decoration-line-hover": "underline",
        "ink": "{app.ink}",
        "ink-hover": "{action.ink}"
      }
    },
    {
      "component": "tabs",
      "name": "code-block",
      "axis": "context",
      "description": "Code and Preview tabs inside the Code Block toolbar.",
      "overrides": {
        "indicator-block-size": "0px",
        "indicator-border-radius": "{border.radius-sm}",
        "indicator-canvas": "{code-block.bar-canvas}",
        "indicator-canvas-active": "{app.border-emphasis}",
        "indicator-canvas-focus": "{focus.color}",
        "indicator-canvas-hover": "{app.border-muted}",
        "indicator-canvas-selected": "{action.border-emphasis}",
        "indicator-canvas-selected-active": "{action.border-emphasis}",
        "indicator-canvas-selected-focus": "{focus.color}",
        "indicator-canvas-selected-hover": "{action.border-emphasis}",
        "tab-border-radius": "{border.radius-sm}",
        "tab-canvas": "{code-block.bar-canvas}",
        "tab-canvas-active": "{action.canvas-emphasis}",
        "tab-canvas-focus": "{code-block.bar-canvas}",
        "tab-canvas-hover": "{code-block.bar-canvas}",
        "tab-canvas-selected": "{action.canvas-emphasis}",
        "tab-canvas-selected-active": "{action.canvas-emphasis}",
        "tab-canvas-selected-focus": "{action.canvas-emphasis}",
        "tab-canvas-selected-hover": "{action.canvas-emphasis}",
        "tab-cursor": "pointer",
        "tab-font-family": "{font-family.interface}",
        "tab-font-size": "{font-size.sm}",
        "tab-font-weight": "{font-weight.medium}",
        "tab-ink": "{action.ink}",
        "tab-ink-active": "{action.ink-inverse-emphasis}",
        "tab-ink-focus": "{action.ink}",
        "tab-ink-hover": "{action.ink}",
        "tab-ink-selected": "{action.ink-inverse-emphasis}",
        "tab-ink-selected-active": "{action.ink-inverse-emphasis}",
        "tab-ink-selected-focus": "{action.ink-inverse-emphasis}",
        "tab-ink-selected-hover": "{action.ink-inverse-emphasis}",
        "tab-letter-spacing": "{letter-spacing.normal}",
        "tab-line-height": "{line-height.2}",
        "tab-min-block-size": "{a11y.min-interaction-size}",
        "tab-min-inline-size": "{a11y.min-interaction-size}",
        "tab-padding-block": "{spacing.2xs}",
        "tab-padding-inline": "{spacing.md}",
        "tab-text-transform": "none",
        "tablist-gap": "{spacing.0}"
      }
    },
    {
      "component": "toggle",
      "name": "icon-only",
      "axis": "size",
      "description": "Suppresses the standard track when a labelled icon is the switch affordance.",
      "overrides": {
        "font-size": "{font-size.xl}",
        "gap": "0",
        "thumb-border-width": "0",
        "thumb-size": "0",
        "track-height": "0",
        "track-width": "0"
      }
    },
    {
      "component": "toggle",
      "name": "theme-icon",
      "axis": "style",
      "description": "Icon-led switch for the site's persisted light and dark themes.",
      "overrides": {
        "border-width": "0",
        "canvas": "transparent",
        "canvas-active": "transparent",
        "canvas-checked": "transparent",
        "canvas-checked-active": "transparent",
        "canvas-checked-hover": "transparent",
        "canvas-hover": "transparent",
        "ink": "{brand.ink-emphasis}"
      }
    }
  ]
};

/** Apply this project's zebkit configuration. Call before defining components. */
export function applyZebkitConfig() {
  ZebkitElement.applyAccessibilityConfig(zebkitConfig.accessibility);
  ZebkitElement.applyComponentsConfig(zebkitConfig.components);
  ZebkitElement.registerVariants(zebkitConfig.variants);
}
