// GENERATED by `zebkit pull`. Do not edit.
export interface ZebkitRuntimeVariant {
  component: string;
  name: string;
  overrides: Record<string, string>;
  axis?: string;
  description?: string;
  className?: string;
}

export type ZebkitRuntimeComponentEntry =
  | boolean
  | { variants?: string[]; options?: Record<string, unknown> };

export interface ZebkitRuntimeConfig {
  zebkitVersion: string;
  themeName: string;
  accessibility: { delivery: 'auto' | 'runtime' | 'precompute' };
  components: Record<string, ZebkitRuntimeComponentEntry>;
  variants: ZebkitRuntimeVariant[];
}

export declare const zebkitConfig: ZebkitRuntimeConfig;

/** Apply this project's zebkit configuration. Call before defining components. */
export declare function applyZebkitConfig(): void;
